development:
  adapter: sqlite
  database: dev.db

test:
  adapter: sqlite
  database: test.db

development:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: warehouse_development
  username: root
  password: root
  socket: /tmp/mysql.sock

development_mysql_jdbc:
  adapter: jdbc
  url: "mysql://localhost/warehouse_development?user=root&password=root"
  charset: utf8
  encoding: utf8

